### ISSUE TITLE
Long Press Gesture (iOS 18 bug?)

### ISSUE THREAD

**Issue by pinefin** [danielsaidi/GestureButton#1]
Let me start of with; I really like this project, it's amazing and it's saved me a lot of time with setting up gestures, this is the first problem I've ran into.

I don't see an issue template, I don't make too many issues on github so I don't know how to structure it so I'll just lay it out...

I'm working with long press gestures. In the simulator (canvas view) I can use long presses just fine (they break after time? I can't recreate this)

But when I launch on my phone I get `<0x10619d400> Gesture: System gesture gate timed out.` error whenever I long press. My phone is on iOS 18 Beta 8 (worried that this might be a iOS 18 bug and not a 17, but I do not have another device to test on)

```Swift
.overlay {
    GestureButton(
        isPressed: $buttonPressed,
        pressAction: {
            print("pressed")
            onButtonPress(true, false)
        }, //
        releaseInsideAction: {
            print("release")
            onButtonPress(false, false)
        },
        releaseOutsideAction: {
            print("release")
            onButtonPress(false, false)
        },
        longPressDelay: data.buttonOnTime,
        longPressAction: {
            print("long press")
            if (data.selectedType == .htl) {
                onButtonPress(false, true)
            }
        },
        endAction: {
            print("end")
            onButtonPress(false, false)
        },
        label: { press in
            Rectangle()
                .fill(Color.clear)
                .contentShape(Rectangle())
                .frame(width: .infinity)
        })
}
```

Here is the code that I'm using. I know it looks not the greatest, but I am having it overlay a image that updates on state changes in the view that surrounds this button, but that's besides the point

...

This is what the output looks like...
![Screenshot 2024-09-09 at 1 36 07 PM](https://github.com/user-attachments/assets/7b590230-572d-4cbf-929d-113fad21e299)

I'm using Swift 6 and XCode 16 (Beta 6). If you need any extra info let me know

**Comment by pinefin** [comment]
Alright I've got a little more info. This button is in a NavigationLink. Whenever I preview just the SimulatorView (the view that this button is in) long press works. Whenever I go from ContentView and open SimulatorView it then fails to send a long press.

Thank you, I'll keep investigating

**Comment by pinefin** [comment]
I've found the issue. It happens when a state change happens in the big view.

I moved it to it's own separate View...

```Swift
struct SimulatorButtonView : View {
    var onButtonPress: ((Bool, Bool) -> Void) //(Pressed, Long Pressed) -> Nothing
    @Binding var longPressDelay : Double
    
    var body : some View {
        GestureButton(
            pressAction: { onButtonPress(true, false) },
            releaseInsideAction: {
                print("release")
                onButtonPress(false, false)
            },
            releaseOutsideAction: {
                print("release")
                onButtonPress(false, false)
            },
            longPressDelay: longPressDelay,
            longPressAction: { print("long press"); onButtonPress(false, true) },
            label: { isPressed in
                Rectangle()
                    .fill(Color.clear)
                    .contentShape(Rectangle()) // Ensure the entire rectangle is tappable
                    .frame(width: .infinity) // Adjust the height as needed
            }
        )
    }
}
```

This fixed my problem so I will close this issue now.

**Comment by danielsaidi** [comment]
Hi @pinefin 

Happy to hear that you like it! :) 

I am using it in another SDK and I found some things to adjust when hammering the button, but other than that I'm pretty happy with the result so far.

Great to see that you found the reason for the strange behavior.
